/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:38:34 CEST 2019
 */

package org.apache.commons.collections.iterators;

import org.junit.Test;

import java.lang.reflect.Array;
import java.util.Comparator;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.ListIterator;

import static org.junit.Assert.*;

public class CollatingIterator_ESTest {
  @Test
  public void collatingIterator_ESTest() {
	// Generated test case for ACC - 377

  }
}
