/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 17 12:19:02 EEST 2019
 */

package org.apache.commons.collections.iterators;

import org.junit.Test;
import static org.junit.Assert.*;

public class CollatingIterator_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
