/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 08 14:38:34 CEST 2019
 */

package org.apache.commons.collections.iterators;

import org.junit.Test;

import java.lang.reflect.Array;
import java.util.Comparator;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.ListIterator;

public class CollatingIterator_ESTest {

    @Test
    public void collatingIterator_ESTest() {
        CollatingIterator collatingIterator0 = new CollatingIterator();
        CollatingIterator collatingIterator1 = new CollatingIterator();
        CollatingIterator collatingIterator2 = new CollatingIterator();
        CollatingIterator collatingIterator3 = new CollatingIterator();
        CollatingIterator collatingIterator4 = new CollatingIterator();
        CollatingIterator collatingIterator5 = new CollatingIterator();
        CollatingIterator collatingIterator6 = new CollatingIterator();
        CollatingIterator collatingIterator7 = new CollatingIterator();
        CollatingIterator collatingIterator8 = new CollatingIterator();
        CollatingIterator collatingIterator9 = new CollatingIterator();
        CollatingIterator collatingIterator10 = new CollatingIterator();
        LinkedList<String> linkedList0 = new LinkedList<String>();
        int int0 = 0;
        String string0 = "";
        String string1 = "B7j,hA`J(\\g)B2$+";
        linkedList0.add(string1);
        ListIterator<String> listIterator0 = linkedList0.listIterator(int0);
        ListIterator<String> listIterator1 = linkedList0.listIterator();
        Comparator<Integer> comparator0 = null;
        collatingIterator8.hasNext();
        Iterator<String>[] iteratorArray0 = (Iterator<String>[]) Array.newInstance(Iterator.class, 5);
        iteratorArray0[0] = (Iterator<String>) collatingIterator0;
        iteratorArray0[1] = (Iterator<String>) listIterator0;
        iteratorArray0[2] = (Iterator<String>) listIterator1;
        iteratorArray0[3] = (Iterator<String>) collatingIterator10;
        iteratorArray0[4] = (Iterator<String>) collatingIterator8;
        CollatingIterator collatingIterator11 = new CollatingIterator(comparator0, iteratorArray0);
        CollatingIterator collatingIterator12 = new CollatingIterator(comparator0, iteratorArray0);
        collatingIterator12.next();
        collatingIterator4.remove();
        collatingIterator4.hasNext();
    }
}
